name: OWASP Dependency Check

on:
  schedule:
    - cron: "1 2 * * FRI"

jobs:
  dependency-check:
    name: analyse with owasp dependency check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache npm dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache pom dependencies
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.m2/repository
            node/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run OWASP dependency check
        run: >
          ./mvnw --batch-mode clean
          frontend:install-node-and-npm
          frontend:npm@install-npm-dependencies
          org.owasp:dependency-check-maven:check
      - uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
