name: Urlaubsverwaltung CI

on: [push]

jobs:
  build:
    name: with jdk ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '12' ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: ./mvnw --batch-mode clean verify sonar:sonar
